// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";
import * as __TAURI_EVENT from "@tauri-apps/api/event";

/** Commands */
export const commands = {
	/**  返回应用与运行时信息。 */
	getAppInfo: () => __TAURI_INVOKE<AppInfo>("get_app_info"),
	/**  返回核心模块清单，供界面展示架构就绪情况。 */
	listCoreModules: () => __TAURI_INVOKE<CoreModule[]>("list_core_modules"),
};

/** Events */
export const events = {
	coreStatus: makeEvent<CoreStatus>("core-status"),
};

/* Types */
/**  应用与运行时的基本信息。 */
export type AppInfo = {
	/**  产品名。 */
	name: string,
	/**  应用版本号。 */
	version: string,
	/**  所依赖的 Tauri 版本。 */
	tauri_version: string,
	/**  目标操作系统，例如 `windows` / `macos` / `linux`。 */
	platform: string,
	/**  目标 CPU 架构，例如 `x86_64` / `aarch64`。 */
	arch: string,
	/**  是否为 debug 构建。 */
	debug: boolean,
};

/**  一个核心模块在界面上的自我描述。 */
export type CoreModule = {
	/**  crate 名。 */
	name: string,
	/**  该模块负责什么。 */
	responsibility: string,
	/**  计划落地的里程碑。 */
	milestone: string,
};

/**
 *  核心运行时状态快照。
 * 
 *  M0 阶段只是一个心跳，用来验证 IPC 事件通道可用；随着 M1/M2 落地，
 *  这里的字段会变成真实的网络与 buffer 计数。
 */
export type CoreStatus = {
	/**
	 *  应用已运行的秒数。
	 * 
	 *  刻意用 `u32` 而非 `u64`：跨 IPC 的整数最终是 JS 的 `number`，
	 *  specta 会直接拒绝导出 64 位整数以避免精度丢失。秒粒度的 u32
	 *  可以表示 136 年，对运行时长完全够用。
	 *  约定见 `docs/实施计划.md` 的「IPC 整数约定」。
	 */
	uptime_seconds: number,
	/**  当前已连接的网络数量。 */
	connected_networks: number,
	/**  当前打开的 buffer 数量。 */
	active_buffers: number,
};

/* Tauri Specta runtime */
type EventEmit<T> = [T] extends [null] ? () => Promise<void> : (payload: T) => Promise<void>;

function makeEvent<T>(name: string, serialize?: (payload: T) => unknown, deserialize?: (payload: any) => T) {
    const mapEvent = (cb: __TAURI_EVENT.EventCallback<T>) => (event: __TAURI_EVENT.Event<any>) => cb({ ...event, payload: deserialize ? deserialize(event.payload) : event.payload });
    const mapPayload = (payload: T) => serialize ? serialize(payload) : payload;

    const base = {
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.listen(name, mapEvent(cb)),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.once(name, mapEvent(cb)),
        emit: ((payload: T) => __TAURI_EVENT.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>
    };

    const fn = (target: import("@tauri-apps/api/webview").Webview | import("@tauri-apps/api/window").Window) => ({
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => target.listen(name, mapEvent(cb)),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => target.once(name, mapEvent(cb)),
        emit: ((payload: T) => target.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>
    });

    return Object.assign(fn, base);
}

